#!/bin/bash
set -e -u -x
export ROOT_DIR=$PWD
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH


go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

cd $GOPATH/src/github.com/deejross/firehose-to-syslog/


make test