#!/bin/bash -exu

MERGED_REPO="${PWD}/${MERGED_REPO:?"MERGED_REPO required"}"
MASTER_BRANCH="${MASTER_BRANCH:-master}"
GIT_USERNAME="${GIT_USERNAME:?"GIT_USERNAME required"}"
GIT_EMAIL="${GIT_EMAIL:?"GIT_EMAIL required"}"

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
set +u
set -u

pushd release-repo > /dev/null
  git config user.name "${GIT_USERNAME}"
  git config user.email "${GIT_EMAIL}"

  git remote add -f master-repo ../release-repo-master
  git merge --no-edit "master-repo/${MASTER_BRANCH}"

  git status
  git show --color | cat
popd > /dev/null

shopt -s dotglob
cp -R release-repo/* $MERGED_REPO
